# Generated by Django 2.0.3 on 2018-03-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(max_length=2)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
