# Generated by Django 2.0.3 on 2018-04-12 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategories',
            fields=[
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='market.Store')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Category')),
            ],
            options={
                'db_table': 'store_categories',
            },
        ),
        migrations.AlterUniqueTogether(
            name='storecategories',
            unique_together={('store', 'category')},
        ),
    ]
